apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: demodb
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              value: user
          image: mysql:9
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 3
          name: db
          resources:
            limits:
              memory: "1G"
              cpu: "500m"
            requests:
              memory: "1G"
              cpu: "250m"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: db-cm0
            - mountPath: /var/lib/mysql
              name: db-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: db-cm0
          name: db-cm0
        - name: db-claim1
          persistentVolumeClaim:
            claimName: db-claim1
