apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-deploy.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: php
  name: php
spec:
  type: ClusterIP
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: php
