apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-deploy.yml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-deploy.yml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: php
    spec:
      containers:
        - image: somkiat/php:1.0
          imagePullPolicy: Always
          name: php
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      restartPolicy: Always
